image: redrock-go
variables:
  REPO_NAME: begonia-rpc

before_script:
  - mkdir -p .cache
  - export GOPATH="$CI_PROJECT_DIR/.cache"
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR/ $GOPATH/src/$REPO_NAME

cache: &global_cache
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cache/
  policy: pull-push

stages:
  - test
  - build
  - deploy

format:
  stage: test
  tags: 
    - redrock-go
  script:
    - cd $GOPATH/src/$REPO_NAME
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)

compile:
  stage: build
  tags: 
    - redrock-go
  script:
    - cd $GOPATH/src/$REPO_NAME
    - go build -ldflags "-extldflags '-static'" -o app ./cmd/main.go
  artifacts:
    paths:
      - app
      
docker: 
  stage: deploy
  when: manual
  tags:
    - redrock-go
  script:
    - mkdir -p data
    - mv app data/app #这条是把二进制移到指定位置，自己修改打包后的二进制名字
    - tar -C data -cf data.tar .
    - curl -F data=@data.tar -X POST http://202.202.43.234/rrapi/deploy/go/begonia-rpc
